version: "3.7"

services:
  app:
    build: .
    image: ymanshur/go-restful:${APP_VERSION:-latest}
    restart: always
    container_name: go-restful
    ports:
      - ${APP_PORT:-8000}:8000
    environment:
      JWT_SECRET: ${JWT_SECRET:?err}
      DB_USER: ${DB_USER:?err}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT:-3306}
      DB_HOST: host.docker.internal
      DB_NAME: ${DB_NAME:?err}

  # app_db:
  #   extends:
  #     file: docker-compose.db.yml
  #     service: db
  #   container_name: go-restful_db

  # app_db_adminer:
  #   extends:
  #     file: docker-compose.db.yml
  #     service: adminer
  #   container_name: go-restful_db_adminer