name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://github.com
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
#     - name: Create .env file
#       env:
#         APP_PORT: ${{ secrets.APP_PORT }}
#         DB_USER: ${{ secrets.DB_USER }}
#         DB_PASS: ${{ secrets.DB_PASS }}
#         DB_HOST: ${{ secrets.DB_HOST }}
#         DB_PORT: ${{ secrets.DB_PORT }}
#         DB_NAME: ${{ secrets.DB_NAME }}
#         JWT_SECRET: ${{ secrets.JWT_SECRET }}
#       run: |
#         touch .env
#         echo APP_PORT=$APP_PORT >> .env
#         echo DB_USER=$DB_USER >> .env
#         echo DB_PASS=$DB_PASS >> .env
#         echo DB_HOST=$DB_HOST >> .env
#         echo DB_PORT=$DB_PORT >> .env
#         echo DB_NAME=$DB_NAME >> .env
#         echo JWT_SECRET=$JWT_SECRET >> .env

#     - name: Test
#       run: go test -v ./...

    - name: Build the Docker image
      run: make build
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push Docker image to Docker Hub
      run: make push

#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3

#     - name: Release a Docker container to Heroku
#       uses: gonuit/heroku-docker-deploy@v1.3.3
#       with:
#         email: ${{ secrets.HEROKU_EMAIL }}
#         heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#         heroku_app_name: go-restful
#         dockerfile_directory: ./
#         dockerfile_name: Dockerfile
#         docker_options: "--no-cache"
#         process_type: web
