name: Docker CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Create .env file
      run: |
        touch .env
        echo APP_PORT=${{ secrets.APP_PORT }} >> .env
        echo DB_USER=${{ secrets.DB_USER }} >> .env
        echo DB_PASS=${{ secrets.DB_PASS }} >> .env
        echo DB_HOST=${{ secrets.DB_HOST }} >> .env
        echo DB_PORT=${{ secrets.DB_PORT }} >> .env
        echo DB_NAME=${{ secrets.DB_NAME }} >> .env
        echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
        
    - name: Test
      run: go test -v ./...

    - name: Build Docker image
      run: make build
